apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec: 
  selector: 
    purpose: service-demo
    project: roboshop
    envirnoment: dev
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port

---
appVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    purpose: service-demo
    project: roboshop
    envirnoment: dev
spec:
  containers:
  - name: nginx
    image: nginx
    